name: NodeModules
description: Cache and Fetch Node dependencies

inputs:
  caching:
    description: enable caching of dependencies
    required: false
    default: true

outputs:
  caching:
    description: report if cache was used
    value: ${{ steps.fetching.outputs.caching }}

runs:
  using: composite
  steps:
    - name: Cache Dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Fetch Dependencies
      if: inputs.caching != 'true' || steps.cache.outputs.cache-hit != 'true'
      id: fetching
      run: |
        npm ci
        echo "caching=${{ inputs.caching }}" >> $GITHUB_OUTPUT
      shell: bash
