name: containers

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      MONGODB_CONNNECTION_PROTOCOL: mopngodb
      MONGODB_CLUTSTER_ADDRESS: mongodb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: secret
    # # specify for this job to be run within a container image
    # container:
    #   image:
    # # specify additional services to make avilable via images
    # services:
    #   mongodb:
    #     image: mongo
    #     env:
    #       MONGO_INITDB_ROOT_USERNAME: root
    #       MONGO_INITDB_ROOT_PASSWORD: secret
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Fetch Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint
        run: npm run lint
