name: Hello
description: Say Hello
runs:
  using: composite
  steps:
    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      shell: bash
    - name: Fetch Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
