comment: |
  Bacon ipsum dolor amet sirloin meatball capicola chislic jerky.
  Tenderloin t-bone sirloin prosciutto, strip steak pastrami 
  frankfurter tri-tip drumstick kevin kielbasa spare ribs burgdoggen.
  Ham hock rump picanha corned beef, burgdoggen ribeye sirloin 
  drumstick short ribs. Chuck frankfurter tenderloin beef tail 
  salami meatball prosciutto. Alcatra boudin strip steak spare 
  ribs capicola sirloin chuck biltong chislic bresaola tail brisket. 
  Flank capicola beef, tail tri-tip andouille alcatra sirloin burgdoggen.

# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

  # trigger this workflow on push to specified branches
  push:
    branches: ["main"]

  # trigger this workflow on pull requests to specified branches
  pull_request:
    branches: ["main"]

  # allow this workflow to be manually triggered from the github ui
  workflow_dispatch:

# A workflow run is made up of one or more jobs
# jobs can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "hello"
  hello:
    # The type of runner that the job will run on
    # see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks to be executed
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,
      - name: Checkout
        # using official github maintained action
        uses: actions/checkout@v3
        # using personal fork of an action
        # uses: russell-palolo/checkout@main

      # Runs a custom action from our repository
      - name: Say Hello
        uses: ./.github/actions/hello

      # Runs a list of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          sleep 3
          echo test, and deploy your project.\
          sleep 2

  build:
    needs:
      - hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Say Hello
        uses: ./.github/actions/hello
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          sleep 3
          echo test, and deploy your project.\
          sleep 2
