name: Output information

on:
  # trigger this workflow on push to specified branches
  push:
    branches:
      - main

    # only run no file changes in one of the paths
    paths-ignore:
      - ".github/actions/*"

  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/en/actions/learn-github-actions/contexts
      - name: Output Github context
        run: echo '${{ toJSON(github) }}'
