name: reusable
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact
        required: false
        default: dist
        type: string
      script-file:
        description: The name of the deployable artifact
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output Build Artifacts
        run: ls -al
      - name: Output Script File Name
        run: echo "${{ inputs.script-file }}"
      - name: Output Information
        run: echo "Deploying & uploading..."
